### ISSUE TITLE
Can't see storage that once used as RSTe.

### ISSUE THREAD

**Issue by ycheng** [dell/dell-recovery#109]
On a machine that once installed windows and RAID on in bios, windows will use the storage in RSTe mode.

Given the status of the storage, the storage won't be display in stage 1 of the OEM image.

Found the code affected is:

        id_type = block.get_cached_property("IdType").get_string()
        if id_type == 'isw_raid_member':
            continue
And the original commit that introduced above is (been refactored by other commits though): 38630b8

Shall we either revert the whole commit, since it seems we are not going to either

1. revert the whole commit
1. comment out the major blocking code
1. keep as is

**Comment by ycheng** [comment]
On a machine that once installed windows and RAID on in bios, windows will use the storage in RSTe mode.

Given the status of the storage, the storage won't be display in stage 1 of the OEM image.

Found the code affected is:

            id_type = block.get_cached_property("IdType").get_string()
            if id_type == 'isw_raid_member':
                continue

And the original commit that introduced above is (been refactored by other commits though):

https://github.com/dell/dell-recovery/commit/38630b804dbca29b9fa0d97641846b7ba388fb8e

Shall we either revert the whole commit, since it seems we are not going to either

1. revert the whole commit
2. comment out the major blocking code
3. keep as is

?

**Comment by superm1** [comment]
What system is this?  What HDD?
Is it production system yet?  Does it use VMD?  I notice you mention RSTe, did you mean RST or RSTe?

**Comment by ycheng** [comment]
I got an DVT2 machine this week and there are two storage.

One is the Intel® Optane Memory H10. It looks like certain windows partition is there.
The other one is a certain general nvme and no partition and no special attribute is there.

dell-recovery can properly show the general nvme, but can't show Intel® Optane Memory H10.

As I comment out the code in dell-recovery mentioned, I can see Intel Optane, and can install the OS onto it.

**Comment by superm1** [comment]
OK so this is a machine with VMD.  That doesn't actually mean that it has RSTe, it should be RST metadata, but operationally it should work pretty similar to the RSTe case.

I think the reason that we skipped the RSTe arrays previously is that installing to them might damage a pre-built multi-disk array.  However that does sound short sighted to me.  I would say that removing that block makes sense but the messaging for the disk needs to make it clear that it's a member of RAID array so you know whether you are destroying an array you might have made in BIOS setup previously.

**Comment by ycheng** [comment]
The motivation is more like to remove those certain in-convenient in the bring up process, and don't harm end-user.

Given that, mind provide your minimal spec for the UI design? For example:

add a "*" in front of those disks with RST metadata, and add one line of text below the selection box to explain what it means?

**Comment by superm1** [comment]
I think your idea is perfect here.
