### ISSUE TITLE
Enhanced sorting storage

### ISSUE THREAD

**Issue by ycheng** [dell/dell-recovery#110]
In https://github.com/dell/dell-recovery/blob/master/ubiquity/dell-bootstrap.py#L651
It just do disks.sort(), and the result seems not quite end-user prefer.
IMHO, for today, we could just put nvme in front of sdX. If we have two nvme disks, put largest disk first seems to be reasonable.

Given above idea, we still need the answer on the sorting order of (include nvme and sd):

/dev/dm
/dev/md
/dev/pmem
/dev/nvme
/dev/sd

**Comment by superm1** [comment]
>IMHO, for today, we could just put nvme in front of sdX. If we have two nvme disks, put largest disk first seems to be reasonable.

Yes, completely agree.

>/dev/dm
/dev/md
/dev/pmem
/dev/nvme
/dev/sd

I think that I would put it in this order:

```
/dev/dm
/dev/md
/dev/nvme
/dev/pmem
/dev/sd
```

With this logic:
* If you have /dev/dm or /dev/md devices those are potentially prepared outside of installer in advance and you probably want to re-use them.
* Persistent memory is generally pretty small, and although fast it's better suited for workloads that operated on it for a database than a general purpose OS.

**Comment by ycheng** [comment]
This committee shall work. Pending: test on more storage combination.
Add test on machine that have sdX and nvme at least.
Feel free to comment on the bug. Let's not merge for now. Let me finish the RST part.

https://github.com/ycheng/dell-recovery/commit/32df5c725dad15bcd5cb8d999e339fd7dc7f5ccd

**Comment by superm1** [comment]
> This committee shall work. Pending: test on more storage combination.
> Add test on machine that have sdX and nvme at least.
> Feel free to comment on the bug. Let's not merge for now. Let me finish the RST part.
> 
> [ycheng@32df5c7](https://github.com/ycheng/dell-recovery/commit/32df5c725dad15bcd5cb8d999e339fd7dc7f5ccd)

Happy with that approach thus far.

**Comment by fourdollars** [comment]
Mario preferred order is occasionally in alphabetical order so it might be done by `disks.sort()`.

**Comment by ycheng** [comment]
disks contain disk which is something like

[devicefile, devicesize, "%s GB %s:%s (%s)" % (devicesize_gb, devicevendor, devicemodel, devicefile)]

device file is something like /dev/sda, /dev/sdb, and their order won't be the order of it's size.

**Comment by ycheng** [comment]
@superm1, 

If we have two or more the same nvme module install on a host. Per reported at least once, we install on a module say /dev/nvme0n1, and after install and boot into OS, it's found to be /dev/nvme1n1.

Given so, I'd like to include serial to the sorting key. Which means:
  If we have more than one module that has the same size, model, they will definitely have a different serial.
  If we add serial to the sorting key, then we could have a more reliable sorting order.

Do you think this idea works for you?

**Comment by superm1** [comment]
I don't see why the SSD order will change from boot to boot. Are you absolutely sure this happened?

**Comment by superm1** [comment]
I guess my main concern here is that a customer who received a machine with factory installed image will not have OS installed onto the first SSD according to sort by serial, but rather to first enumerated by firmware.

If they boot USB recovery media the first offered disk might not be the same because serial number was sorted.

So if serial number is used for a sort key in identical disk scenario then I think we would also need to show which have existing content which might be too much for that single box.

**Comment by ycheng** [comment]
Ok, for the serial as part of sorting key, the one that I remember once reproduce is occupied.

Given so, the plan is to skip it for now. I'll work on the other ticket, and shell able to have another commit soon.

**Comment by ycheng** [comment]
Thank you.
