### ISSUE TITLE
dell-recovery treat the removed ubiquity as error when there's new version of ubiquity in debs folder

### ISSUE THREAD

**Issue by alex-tu-cc** [dell/dell-recovery#113]
regarding to the behavior of ubiquity during image installation, the ubiquity debian package will be uninstalled in the end.
Then because dell-recovery set a guard to treat packages removing which installed by ubiquity operations as a failure [1].

So, dell-recovery treat the removed ubiquity as error when there's new version of ubiquity in debs folder.
The failure checking should filter out the ubiquity packages.

[1] https://github.com/dell/dell-recovery/blob/master/late/scripts/chroot.sh#L170

**Comment by superm1** [comment]
Thanks for your fix to this, makes sense!
