### ISSUE TITLE
automatic mode enhancement

### ISSUE THREAD

**Issue by ycheng** [dell/dell-recovery#117]
The idea is: in development phase, install from usb still is the most stable way.
For engineer, save time and less interactivity in repeated process helps a lot.

So I'd like a way to easily and enable full-automatic installation/recovery mode.

Full picture:
1. modify oobe so that it's full-automatic if automatic mode in ubiquity is enable.
2. enable full-automatic mode in stage 1, 2 and recovery from hdd
3. a way to preseed oobe. either make sure we can preseed stage 1, 2 can properly carry those to oobe (by ubiquity), or we can add oobe specific preseed.
4. enable automatic mode in oobe.

We current have other way to do 3 and 4. Even better if that's built-in in dell-recovery.

**Comment by ycheng** [comment]
Updated PR in https://github.com/dell/dell-recovery/pull/118

**Comment by ycheng** [comment]
Another idea (to be implemented) is to add another attribute to recovery_type, say a Boolean value as full_automatic.

**Comment by superm1** [comment]
#118 was merged, closing
