### ISSUE TITLE
build error with proposed pyflakes3 2.2.0-1~20.04.1

### ISSUE THREAD

**Issue by alex-tu-cc** [dell/dell-recovery#120]
./tests/run-pyflakes
Dell/recovery_backend.py:563:21 local variable 'timestamp' is assigned to but never used
Dell/recovery_backend.py:564:21 local variable 'distributor_string' is assigned to but never used
Dell/recovery_common.py:653:25 local variable 'type' is assigned to but never used
Dell/recovery_basic_gtk.py:157:72 local variable 'wfd' is assigned to but never used
make[1]: *** [debian/rules:17: check] Error 1
make[1]: Leaving directory '/home/alextu/workspace/PC/somerville/tasks/recovery/dell-recovery'
make: *** [debian/rules:7: clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2

**Comment by superm1** [comment]
I've fixed these in master, and they're also blocking groovy movement, so i'll flush out the recent work into a new release for groovy.
