### ISSUE TITLE
Travis-ci: Error while enabling ppc64le build 

### ISSUE THREAD

**Issue by sanjay-cpu** [dell/dell-recovery#124]
Hi ,

I am enabling ppc64le build on travis-ci, and updated the .travis.yml and added arch: ppc64le along with amd64. But ppc64le build is failing and below error is coming:  

"E: Unable to locate package gnu-efi
The command '/bin/sh -c apt-get install -yq --no-install-recommends 	build-essential 	debhelper 	dh-python 	dpkg-dev 	python3 	python3-distutils-extra 	po-debconf 	pyflakes3 	lsb-release 	gnu-efi' returned a non-zero code: 100
The command "docker build -t dell-recovery-ubuntu -f docker/Dockerfile-ubuntu ." failed and exited with 100 during .
Your build has been stopped."

Full error log can be tracked on this link 👍 https://travis-ci.com/github/sanjay-cpu/dell-recovery/jobs/386367642

Please have a look into the issue.

Thanks !!

**Comment by superm1** [comment]
Dell doesn't ship ppc64le hardware, and this project is intended to support Dell's client hardware. So I don't think it's worth the effort to add CI like that.

**Comment by sanjay-cpu** [comment]
@superm1 Thanks !!
