### ISSUE TITLE
to support Intel and AMD SDP (dev board)

### ISSUE THREAD

**Issue by alex-tu-cc** [dell/dell-recovery#138]
To support cutting-edge hardware, it would be more efficient if Intel and AMD can verify the latest OEM image on their dev board.
Can we also cover Intel and AMD SDP in the allowing list of dell-recovery?

The line to get this extending should be https://github.com/dell/dell-recovery/blob/master/Dell/recovery_common.py#L216

**Comment by alex-tu-cc** [comment]
@CragW How do you think of this idea? If you approve this idea, I can submit a pull request for it.

**Comment by CragW** [comment]
Sounds good to me. Do you see other identity that is helpful to determine a dev board in addition to vendor string? That is we can set a smaller set for development use.

**Comment by CragW** [comment]
I'm not sure but wondering if /proc/* talks its identity? For instance /proc/cpuinfo

**Comment by alex-tu-cc** [comment]
thanks for support this idea, I will check some SDP we have.

**Comment by alex-tu-cc** [comment]
For intel:
/sys/class/dmi/id/board_name
TigerLake H DDR4 SODIMM RVP
/sys/class/dmi/id/board_vendor
Intel Corporation

**Comment by alex-tu-cc** [comment]
For Intel:
$ cat /sys/class/dmi/id/bios_vendor
Intel Corporation

# the other dmi value related to dev board.
$ cat /sys/class/dmi/id/board_name
CometLake H SODIMM RVP4

We only have one AMD SDP, maybe you have more sample for checking:
$ cat /sys/class/dmi/id/board_vendor
AMD

# there is no other dmi value providing the information about if it is a dev board.

**Comment by alex-tu-cc** [comment]
@CragW how do you think for the MP, or do you have some more Intel or AMD SDP which provide different dmi information?

**Comment by alex-tu-cc** [comment]
@superm1 Hi Mario, Crag told me that you have some way to identify the AMD dev board (or called CRB), could you please share us the way and the related message? Or if there's no way to identify AMD dev board, do you think this patch is good for you?

**Comment by superm1** [comment]
I think this method you did should scale fine for now.

**Comment by CragW** [comment]
ok, let's go ahead without specified to dev boards.
