### ISSUE TITLE
.disk/casper-uuid is missing and conf/uuid.conf in initrd is not updated for jammy

### ISSUE THREAD

**Issue by fourdollars** [dell/dell-recovery#156]
I made a customized Ubuntu jammy image with dell-recovery.
I can boot from Ubuntu system on the USB stick to execute dell-recovery to install the recovery partition. (stage1)
However .disk/casper-uuid is missing and conf/uuid.conf in initrd is not updated in the recovery partition. (stage2)
So it won't boot from the recovery partition to install Ubuntu system. (It can not enter stage2.)

**Comment by fourdollars** [comment]
I found something in bto.xml in the recovery partition.
```
Mar 14 14:08:30 ubiquity: ['log-output', '-t', 'ubiquity', '--pass-stdout', '/usr/share/ubiquity/dell-bootstrap'] exited with code 0
ERROR:root:Could not update progress:
Traceback (most recent call last):
  File &quot;/usr/lib/python3/dist-packages/Dell/recovery_threading.py&quot;, line 82, in run
    if callable(self.progress):
  File &quot;/usr/lib/python3/dist-packages/Dell/recovery_threading.py&quot;, line 34, in callable
    return isinstance(obj, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by fourdollars** [comment]
After I solved the AttributeError above, it still has the same issue.

**Comment by CragW** [comment]
> After I solved the AttributeError above, it still has the same issue.

It looks like jammy switched to `zstd` to compressing its initramfs therefore `compression command` is not found, can you please send a PR to fix this issue?

**Comment by fourdollars** [comment]
Sorry. It is my fault that I didn't copy Dell grub theme into the image.
