### ISSUE TITLE
/var/log/installer/casper-md5check.json has a failed result.

### ISSUE THREAD

**Issue by fourdollars** [dell/dell-recovery#166]
When I used somerville-jammy-amd64-20220504-33.iso or dell-bto-jammy-jellyfish-X07-20220504-12.iso based on somerville-jammy-amd64-20220504-33.iso, both of them will generate the failed result in /var/log/installer/casper-md5check.json.
But there is no problem to execute `md5sum -c md5sum.txt --quiet` to check the base image, i.e somerville-jammy-amd64-20220504-33.iso,  directly.
So dell-recovery needs to fix the problem when it generated the recovery image or created the recovery partition.

**Comment by fourdollars** [comment]
Before applying the patch, /var/log/installer/casper-md5check.json shows something like:
```
{
  "checksum_missmatch": [ 
    "./bto.xml",
    "./.disk/casper-uuid",
    "./boot.catalog",
    "./EFI/boot/bootx64.efi",
    "./EFI/boot/mmx64.efi",
    "./EFI/boot/grubx64.efi",
    "./boot/grub/i386-pc/eltorito.img",
    "./.disk/casper-uuid-oem"
],
  "result": "fail"
}
```

After apllying the patch, it shows something like:
```
{
  "checksum_missmatch": [],
  "result": "pass"
}
```

**Comment by fourdollars** [comment]
I followed Ubuntu 22.04 ISO to ignore some files in md5sums.txt.

**Comment by CragW** [comment]
These files should have been covered by `regenerate_md5sum`, any post-modifications after that?
```
    "./bto.xml",
    "./.disk/casper-uuid",
    "./.disk/casper-uuid-oem"
```
These files are introduced by cd-boot-images, do you want incorporate them into `regenerate_md5sum`?
```
    "./EFI/boot/bootx64.efi",
    "./EFI/boot/mmx64.efi",
    "./EFI/boot/grubx64.efi",
    "./boot/grub/i386-pc/eltorito.img",
```
The new `xorriso` commands generates this file at ISO's build time hence it makes sense to be excluded.
```
    "./boot.catalog",
```

**Comment by fourdollars** [comment]
Because Ubuntu 22.04 ISO image doesn't include the md5sum for the following files:
```
    "./EFI/boot/bootx64.efi",
    "./EFI/boot/mmx64.efi",
    "./EFI/boot/grubx64.efi",
    "./boot/grub/i386-pc/eltorito.img",
```
So I just followed Ubuntu 22.04 ISO image.

These files will be changed during the installation:
```
    "./bto.xml",
    "./.disk/casper-uuid",
    "./.disk/casper-uuid-oem"
```

**Comment by fourdollars** [comment]
FYI, you can download ubuntu-22.04-desktop-amd64.iso from https://releases.ubuntu.com/22.04/.
