### ISSUE TITLE
swap file instead of swap partition

### ISSUE THREAD

**Issue by superm1** [dell/dell-recovery#25]
For Ubuntu 17.04 there are some changes potentially going into Ubiquity that will change the defaults to create swap files instead of swap partitions.  

This should be monitored, if that change remains for Ubuntu 18.04 dell-recovery should make a similar change.

**Comment by kevinkellyspacey** [comment]
Got it. Thanks. Are we available to get this kind of change of 17.04 like some link to check in advance?

**Comment by superm1** [comment]
@kevinkellyspacey 
Yes it has made it into Ubuntu 17.04, and will be present in newer Ubuntu images too.
http://linuxbsdos.com/2017/04/18/swap-partition-out-swap-file-in-on-ubuntu-17-04/

The dell-recovery recipes will need to be adjusted to do this too.  

I would recommend:
1. Make an dell-recovery ISO using the regular public ubuntu 17.04 as the "Base" image to start.  This codepath hasn't been tested in a while, so it may have some problems that need to be sorted (missing dependencies i think is the most likely problem - you can add these manually into debs/ to make it work for now).
2. Once you have a dell-recovery ISO using that ubuntu 17.04 as base, make sure it installs.
3. Once you know it installs modify the disk recipe (and any associated code) to take into account making a swap file instead of a swap partition.
4. Ideally make the changes such that you can query the version of Ubuntu being run on.  If it's < 17.04 use swap partition, if it's 17.04+ use swapfile.  That would allow continuing to use a newer dell-recovery code base on older Ubuntu without swapfile support still.

**Comment by kevinkellyspacey** [comment]
Thanks for your sharing. I will keep an eye on it and prepare for this change in advance.

**Comment by superm1** [comment]
@kevinkellyspacey I've pushed some stuff that fixes the dependencies.  You should be able to build using generic ubuntu 17.04 ISO's as the base now.

The swapfile stuff might be as simple as turning off swap in the disk recipe and a swapfile is automatically made, but if not you'll have to dig around some more.

**Comment by kevinkellyspacey** [comment]
OK, I have downloaded the latest public 17.04 image and do some tests. While I am not very sure about "using generic ubuntu 17.04 ISO's as the base" ,since our Dell image has some different parts compared with public one. Would you please help guide more details? Thanks.

**Comment by superm1** [comment]
1. Launch `dell-recovery` in `--builder` mode (as described here: https://github.com/dell/dell-recovery/blob/master/modifying_factory_image.md)
2. For the base ISO image, select Ubuntu 17.04 public image.
3. When prompted, select the dell-recovery debian package built from git master.
4. Don't select apps or drivers

You should get out an ISO image that will run dell-recovery directly.

**Comment by kevinkellyspacey** [comment]
Thanks for your tips. I have done the swap file part with unit test passed.

**Comment by superm1** [comment]
This was fixed in https://github.com/dell/dell-recovery/commit/ca71927867883c1bd88f3b3c08aedd8a2e63cd7d just forgot to close issue.
