### ISSUE TITLE
/usr/share/dell/bin/dell-bto-autobuilder generates ISO images with wrong partition ID.

### ISSUE THREAD

**Issue by fourdollars** [dell/dell-recovery#35]
There is no obvious side effect from this issue so far.

```
$ file italia_X80.iso
italia_X80.iso: DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'ISOIMAGE' (bootable); partition 1 : ID=0x83, start-CHS (0x0,0,1), end-CHS (0x3fb,128,32), startsector 0, 4210560 sectors; partition 2 : ID=0xef, start-CHS (0x3fc,0,1), end-CHS (0x3fd,128,32), startsector 4210560, 8256 sectors
```
```
$ fdisk -l italia_X80.iso 
Disk italia_X80.iso: 2 GiB, 2160033792 bytes, 4218816 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device          Boot   Start     End Sectors Size Id Type
italia_X80.iso1            0 4210559 4210560   2G 83 Linux
italia_X80.iso2      4210560 4218815    8256   4M ef EFI (FAT-12/16/32)
```
```
$ file ubuntu-16.04.3-desktop-amd64.iso
ubuntu-16.04.3-desktop-amd64.iso: DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Ubuntu 16.04.3 LTS amd64' (bootable); partition 2 : ID=0xef, start-CHS (0x3ff,254,63), end-CHS (0x3ff,254,63), startsector 3006684, 4672 sectors
```
```
$ fdisk -l ubuntu-16.04.3-desktop-amd64.iso
Disk ubuntu-16.04.3-desktop-amd64.iso: 1.5 GiB, 1587609600 bytes, 3100800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x0d66cd15

Device                            Boot   Start     End Sectors  Size Id Type
ubuntu-16.04.3-desktop-amd64.iso1 *          0 3100799 3100800  1.5G  0 Empty
ubuntu-16.04.3-desktop-amd64.iso2      3006684 3011355    4672  2.3M ef EFI (FAT-12/16/32)
```

(Edited to place in triple tick code blocks)

**Comment by superm1** [comment]
The way this is generated is intentional to be able to support dd the iso. Does that not work properly for you?

**Comment by superm1** [comment]
Looking more closely at difference with Ubuntu iso I think you're actually referring to partition 1 right? Just the id is different.

**Comment by superm1** [comment]
So i think the main difference between generic Ubuntu image and image generated by `dell-bto-autobuilder` is that first partition in partition table.  Do you know if generic Ubuntu image is also made by `xorriso`?  It would be good to compare the arguments used to generate that image.

If `xorriso `is used, i'm guessing this is the missing option:

> zero_mbrpt" demands to zeroize the MBR partition table if bytes 510 and 511 bear the MBR signature 0x55 0xaa. [1]

[1] https://www.gnu.org/software/xorriso/man_1_xorriso_devel.html


That being said, I would be interested to know also if this difference breaks any tools.  I would expect BIOS doesn't care about the partition ID as long as it's not FAT or NTFS.

**Comment by fourdollars** [comment]
There are two differences, one is the boot flag and the other is the partition ID.
I don't know how generic Ubuntu image is made.
My current idea is to find out how to set the boot flag and change the partition ID by xorriso.
Although there is no known issue for the differences so far, it might be better to keep them identical to prevent from any unknown issue in the future.

**Comment by fourdollars** [comment]
I found if I follow the command of http://wiki.osdev.org/El-Torito#Hybrid_Setup_for_BIOS_and_EFI_from_CD.2FDVD_and_USB_stick.
I can build up the right ISO image by the command directly, but when I try to integrate it into recovery_backend.py, the ISO image made by dell-bto-autobuilder can not be booted into the Linux system.

**Comment by fourdollars** [comment]
diff --git a/Dell/recovery_backend.py b/Dell/recovery_backend.py
index c2c78cb..c94f54e 100644
--- a/Dell/recovery_backend.py
+++ b/Dell/recovery_backend.py
@@ -884,7 +884,6 @@ arch %s, distributor_str %s" % (bto_version, distributor, release, arch, distrib
                        '-J',
                        '-joliet-long',
                        '-l',
-                       '-cache-inodes',
                        '-iso-level', '3',
                        '-A', 'Dell Recovery',
                        '-p', 'Dell',
@@ -895,20 +894,32 @@ arch %s, distributor_str %s" % (bto_version, distributor, release, arch, distrib
                        '-m', 'syslinux',
                        '-m', 'syslinux.cfg',
                        '-m', os.path.join(mntdir, 'bto.xml'),
-                       '-m', os.path.join(mntdir, 'isolinux'),
                        '-m', os.path.join(mntdir, 'bto_version')]
 
+        if os.path.exists(os.path.join('/', 'usr', 'lib', 'ISOLINUX', 'isohdpfx.bin')) and \
+            os.path.exists(os.path.join(mntdir, 'isolinux', 'boot.cat')) and \
+            os.path.exists(os.path.join(mntdir, 'isolinux', 'isolinux.bin')):
+            xorrisoargs.append('-c')
+            xorrisoargs.append('isolinux/boot.cat')
+            xorrisoargs.append('-b')
+            xorrisoargs.append('isolinux/isolinux.bin')
+            xorrisoargs.append('-no-emul-boot')
+            xorrisoargs.append('-boot-load-size')
+            xorrisoargs.append('4')
+            xorrisoargs.append('-boot-info-table')
+            xorrisoargs.append('-isohybrid-mbr')
+            xorrisoargs.append(os.path.join('/', 'usr', 'lib', 'ISOLINUX', 'isohdpfx.bin'))
+        else:
+            xorrisoargs.append('-m')
+            xorrisoargs.append(os.path.join(mntdir, 'isolinux'))
+
         #include bootloader as eltorito if we have it
         if os.path.exists(os.path.join(mntdir, 'boot', 'efi.img')):
+            xorrisoargs.append('-eltorito-alt-boot')
             xorrisoargs.append('-e')
             xorrisoargs.append('boot/efi.img')
             xorrisoargs.append('-no-emul-boot')
-            xorrisoargs.append('-append_partition')
-            xorrisoargs.append('2')
-            xorrisoargs.append('0xef')
-            xorrisoargs.append(os.path.join(mntdir, 'boot', 'efi.img'))
-            xorrisoargs.append('-partition_cyl_align')
-            xorrisoargs.append('all')
+            xorrisoargs.append('-isohybrid-gpt-basdat')
 
         #disable 32 bit bootloader if it was there.
         grub_path = os.path.join(mntdir, 'boot', 'grub', 'i386-pc')
diff --git a/debian/control b/debian/control
index 3848eca..d104f8e 100644
--- a/debian/control
+++ b/debian/control
@@ -27,12 +27,13 @@ Depends: ${python3:Depends},
          uuid-runtime,
 Replaces: dell-artwork, dell-oobe
 Conflicts: dell-oobe
-Recommends: usb-creator-gtk,
-            xorriso,
-            dvd+rw-tools,
+Recommends: dvd+rw-tools,
+            isolinux,
             lsb-release,
             parted,
-            python3-progressbar
+            python3-progressbar,
+            usb-creator-gtk,
+            xorriso
 Enhances: oem-config-gtk, ubiquity-frontend-gtk

**Comment by fourdollars** [comment]
xorriso -as mkisofs -R -r -J -joliet-long -l -iso-level 3 -o output.iso -c isolinux/boot.cat -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -eltorito-alt-boot -e boot/efi.img -no-emul-boot -isohybrid-gpt-basdat /mnt # mount some dell-bto image on /mnt.

**Comment by superm1** [comment]
So part of the difference here is that dell-recovery intentionally does not include any legacy support whatsoever.  The dell-recovery images should never be booted in legacy mode and hence don't have a bootloader included for MBR boot.  If it turns out that a change needs to be made to include what looks like an MBR it's better to have a file dd'ed from /dev/zero that's identically sized in it's place.

**Comment by fourdollars** [comment]
I found my system doesn't install casper and it causes the system booting failed.

**Comment by fourdollars** [comment]
I am trying `dd if=/dev/zero of=some.iso bs=432 count=1 conv=notrunc`.

**Comment by fourdollars** [comment]
`dd` may be not a good way.
If I boot from CD/DVD drive, it still works.
Maybe we can break the isolinux boot up process intentionally.

**Comment by superm1** [comment]
What's wrong to just not include MBR boot record and just GPT?

**Comment by fourdollars** [comment]
`dd if=/dev/zero of=some.iso bs=432 count=1 conv=notrunc` will halt the boot process in legacy BIOS mode.

**Comment by fourdollars** [comment]
dell-bto-autobuilder also depends on dell-recovery-casper to build a workable installation media.

**Comment by fourdollars** [comment]
The following patch can make the image almost identical to Ubuntu stock image.
```
diff --git a/Dell/recovery_backend.py b/Dell/recovery_backend.py
index c2c78cb..1b8db2f 100644
--- a/Dell/recovery_backend.py
+++ b/Dell/recovery_backend.py
@@ -884,8 +884,9 @@ arch %s, distributor_str %s" % (bto_version, distributor, release, arch, distrib
                        '-J',
                        '-joliet-long',
                        '-l',
-                       '-cache-inodes',
                        '-iso-level', '3',
+                       '-sysid', 'Linux',
+                       '-V', 'Dell Recovery Media',
                        '-A', 'Dell Recovery',
                        '-p', 'Dell',
                        '-publisher', 'Dell',
@@ -895,20 +896,29 @@ arch %s, distributor_str %s" % (bto_version, distributor, release, arch, distrib
                        '-m', 'syslinux',
                        '-m', 'syslinux.cfg',
                        '-m', os.path.join(mntdir, 'bto.xml'),
-                       '-m', os.path.join(mntdir, 'isolinux'),
                        '-m', os.path.join(mntdir, 'bto_version')]
 
+        if os.path.exists(os.path.join('/', 'usr', 'lib', 'ISOLINUX', 'isohdpfx.bin')) and \
+            os.path.exists(os.path.join(mntdir, 'isolinux', 'boot.cat')) and \
+            os.path.exists(os.path.join(mntdir, 'isolinux', 'isolinux.bin')):
+            xorrisoargs.append('-c')
+            xorrisoargs.append('isolinux/boot.cat')
+            xorrisoargs.append('-b')
+            xorrisoargs.append('isolinux/isolinux.bin')
+            xorrisoargs.append('-no-emul-boot')
+            xorrisoargs.append('-boot-load-size')
+            xorrisoargs.append('4')
+            xorrisoargs.append('-boot-info-table')
+            xorrisoargs.append('-isohybrid-mbr')
+            xorrisoargs.append(os.path.join('/', 'usr', 'lib', 'ISOLINUX', 'isohdpfx.bin'))
+
         #include bootloader as eltorito if we have it
         if os.path.exists(os.path.join(mntdir, 'boot', 'efi.img')):
+            xorrisoargs.append('-eltorito-alt-boot')
             xorrisoargs.append('-e')
             xorrisoargs.append('boot/efi.img')
             xorrisoargs.append('-no-emul-boot')
-            xorrisoargs.append('-append_partition')
-            xorrisoargs.append('2')
-            xorrisoargs.append('0xef')
-            xorrisoargs.append(os.path.join(mntdir, 'boot', 'efi.img'))
-            xorrisoargs.append('-partition_cyl_align')
-            xorrisoargs.append('all')
+            xorrisoargs.append('-isohybrid-gpt-basdat')
 
         #disable 32 bit bootloader if it was there.
         grub_path = os.path.join(mntdir, 'boot', 'grub', 'i386-pc')
diff --git a/debian/control b/debian/control
index 3848eca..d104f8e 100644
--- a/debian/control
+++ b/debian/control
@@ -27,12 +27,13 @@ Depends: ${python3:Depends},
          uuid-runtime,
 Replaces: dell-artwork, dell-oobe
 Conflicts: dell-oobe
-Recommends: usb-creator-gtk,
-            xorriso,
-            dvd+rw-tools,
+Recommends: dvd+rw-tools,
+            isolinux,
             lsb-release,
             parted,
-            python3-progressbar
+            python3-progressbar,
+            usb-creator-gtk,
+            xorriso
 Enhances: oem-config-gtk, ubiquity-frontend-gtk
 Suggests: grub-pc
 Description: Dell Recovery Media Creation Package
```

**Comment by superm1** [comment]
That code seems to break things for me when built on xenial.  It looks like this now:

```
$ file /tmp/ubuntu-16.04-amd64-dell_X00.iso 
/tmp/ubuntu-16.04-amd64-dell_X00.iso: DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Dell Recovery Media' (bootable); partition 1 : ID=0x17, active, start-CHS (0x0,0,1), end-CHS (0x3fb,88,32), startsector 0, 2904960 sectors

$ fdisk -l /tmp/ubuntu-16.04-amd64-dell_X00.iso                                                                                                           
Disk /tmp/ubuntu-16.04-amd64-dell_X00.iso: 1.4 GiB, 1487339520 bytes, 2904960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x6a2635a7

Device                                Boot Start     End Sectors  Size Id Type
/tmp/ubuntu-16.04-amd64-dell_X00.iso1 *        0 2904959 2904960  1.4G 17 Hidden HPFS/NTFS
```

**Comment by fourdollars** [comment]
That's weird. It works fine on my xenial.

`/usr/share/dell/bin/dell-bto-autobuilder -d /tmp/btobuild.cOBZJz/manifest.fish -b /home/sylee/projects/somerville/images/somerville-xenial-amd64-rebase-iso-hybrid-20170712-0.iso --target-name=italia_X80 --target-dir=/home/sylee/projects/oem
`
```
$ fdisk -l /home/sylee/projects/oem/italia_X80.iso
Disk /home/sylee/projects/oem/italia_X80.iso: 2 GiB, 2157920256 bytes, 4214688 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x17b9baf5

Device                                   Boot Start     End Sectors  Size Id Type
/home/sylee/projects/oem/italia_X80.iso1 *        0 4214687 4214688    2G  0 Empty
/home/sylee/projects/oem/italia_X80.iso2       2224    6959    4736  2.3M ef EFI (FAT-12/16/32)

```

**Comment by fourdollars** [comment]
Can we change the syslinux/isolinux config to prevent from booting the Linux kernel?
For example,
![virtualbox_ubuntu_13_09_2017_18_02_48](https://user-images.githubusercontent.com/39708/30371745-19c73be0-98ae-11e7-9083-e8e1aee9dbdb.png)

**Comment by superm1** [comment]
I like that approach alot.
