### ISSUE TITLE
update package which installed in base image cause error.

### ISSUE THREAD

**Issue by alex-tu-cc** [dell/dell-recovery#47]
the commit "f352bd" for https://github.com/dell/dell-recovery/issues/28 will break base image packages updating. 

example:
1. create a usb disk with ubuntu recovery iso content.
2. collect newer mesa stuff from x-staging[1] and x-swat[2] and put them to /debs for update.
  * ex. one of the stuff is libdrm2_2.4.83-1~16.04.1_amd64.deb
3. do recovery from usb disk
4. an older libdrm2 has been installed in base image, so /var/lib/ubiquity/installed-packages exists libdrm2:amd64
5. then it will treat "libdrm2" differ to "libdrm2:amd64" then get a failed result in the code of commit "f352bd".

Then the failure cause showing a red error grub menu in next usb recovery booting.

Should we filter out ":amd64" from comparing?

[1] https://launchpad.net/~canonical-x/+archive/ubuntu/x-staging
[2] https://launchpad.net/~ubuntu-x-swat/+archive/ubuntu/updates/+packages

**Comment by fourdollars** [comment]
Could we just revert the commit "f352bd"?
We don't have much time to debug and fix the regression from it.

**Comment by superm1** [comment]
Pulled in the fix here.
