### ISSUE TITLE
failed record in recovery partition will be copy to created iso.

### ISSUE THREAD

**Issue by alex-tu-cc** [dell/dell-recovery#49]
reproduce step:
 1. do recovery from usb disk and select chinese language
 2. after 1. finished execute 'dell-recovery' to do recovery again.
 3. after 2. finished , execute 'dell-recovery'  to create recovery iso.
 4. use the created iso to do recovery again and get red error grub menu.

Because of #47, the environment in 2 have ${recovery-partition}/factory/grubenv with error bit. So, the ISO generated by 3 will also have it. So that introduce the error in 4.

dell-recovery should stop process and warn user if current environment is not correct. ex. ${recovery-partition}/factory/grubenv should not be there, otherwise the red grub menu will confuse user because there are no error in creating iso.

**Comment by superm1** [comment]
Although the fix for #47 should fix this, I think it makes sense to also filter `grubenv `from being put into a recovery ISO.  Even if there was a failure on the local disk, that should never propagate into a recovery disk.

**Comment by superm1** [comment]
Closed with https://github.com/dell/dell-recovery/commit/7586c9ecf336f8b454259c8f45ee533dcfece89f
