### ISSUE TITLE
The installation on Intel RSTe SATA RAID failed.

### ISSUE THREAD

**Issue by fourdollars** [dell/dell-recovery#67]
When the volume name of RSTe SATA RAID has no number, such as 'RSTe' and 'raid', it will fail to install the system.

**Comment by superm1** [comment]
Can you capture log from the failure?

**Comment by fourdollars** [comment]
I didn't see any failure.
It just stalled in the middle.

**Comment by superm1** [comment]
Can you switch to VT during this time and check syslog?

**Comment by fourdollars** [comment]
https://paste.ubuntu.com/p/ypbx2kSwSp/ /var/log/syslog

**Comment by fourdollars** [comment]
I think I know what is going on.
When the device node ended with number, such as /dev/mapper/isw_ibeahfgeh_raid1, the following partition device node will become /dev/mapper/isw_ibeahfgeh_raid1p1.
But when the device node ended without number, such as /dev/mapper/isw_ibeahfgeh_raid, the following partition device node will become /dev/mapper/isw_ibeahfgeh_raid1.
The original implementation doesn't consider this naming convention and it just assumed the device node will always end with number.
