### ISSUE TITLE
BIOS ID should be identified by tag instead string number.

### ISSUE THREAD

**Issue by alex-tu-cc** [dell/dell-recovery#72]
from the commit fe685de37b0b56127e61bbf59ebde48664c153a6 , the BIOS ID came from string 2, but it should came from tag ID '1' instead.

late/chroot_scripts/03-ubuntu-drivers.sh:
https://paste.ubuntu.com/p/BqnHVFWGzt/

**Comment by superm1** [comment]
Thanks, fixed by your PR https://github.com/dell/dell-recovery/commit/96372438a6790837c0f3cdb0de1baf491484ea50
