### ISSUE TITLE
This tool is incomprehensible to end users, especially when attempting to create dell installation media from a stock standard ubuntu installation. 

### ISSUE THREAD

**Issue by forestjohnsonpeoplenet** [dell/dell-recovery#77]
There needs to be an explanation of where to get this file:

![image](https://user-images.githubusercontent.com/19273873/53107564-dc0fc480-34fa-11e9-8d54-6deaafc0c7be.png)

![image](https://user-images.githubusercontent.com/19273873/53107581-e3cf6900-34fa-11e9-8fb3-4197340da0a9.png)

As a user, I have no idea what this thing is asking me for, and I have no course of action to take. Looking it up hasnt helped much.

**Comment by superm1** [comment]
I guess I should ask - what are you trying to do with it?

Most people use it on a preloaded system and it runs in a different mode.

**Comment by forestjohnsonpeoplenet** [comment]
I am trying to Install Ubuntu 18.04 LTS on a lattitude 5591

I first tried installing it from the standard ISO image from canonical, written to USB by Balena Etcher. I was able to complete the installation process up to the 1st boot after the installer completes.  The computer appears to hard freeze and hangs, like a kernel panic, during the process of booting. Happened once while loading the desktop after inputting the user password, happened once on the cryptsetup screen after inputting the LVM full disk encryption pass phrase 

I read here: https://certification.ubuntu.com/hardware/201803-26137/

**Comment by forestjohnsonpeoplenet** [comment]
Oops didn't mean to close the issue, I read here https://certification.ubuntu.com/hardware/201803-26137/

> Please note that for pre-installed systems:
> The system is available in some regions with a special image of Ubuntu pre-installed by the manufacturer. It takes advantage of the hardware features for this system and may include additional software. You should check when buying the system whether this is an option.
> Standard images of Ubuntu may not work at all on the system or may not work well, though Canonical and computer manufacturers will try to certify the system with future standard releases of Ubuntu.

I was hoping that if I could generate the image which is certified to work, then I would be able to get Ubuntu working on this machine.

That said, maybe I am barking up the wrong tree. I see that page says version 16.04 is certified and I'm trying to install 18.04  here.

**Comment by forestjohnsonpeoplenet** [comment]
Given that I have a Lattitude 5591 and I want to run linux on it, preferably debian based / ubuntu, how should I proceed ?

Is it supposed to work when you install it via Canonical's standard image? Do I have to install an old version? 

I am upgrading from a Lattitude E6540 which has worked flawlessly with Ubuntu 18.04 up to this point (besides running out of RAM occasionally -- hence the upgrade :) )

**Comment by forestjohnsonpeoplenet** [comment]
I think this is what I wanted: https://askubuntu.com/questions/1094697/install-ubuntu-mate-on-latitude-5591-ssd

It sounds like the nvidia driver is crashing it.

**Comment by superm1** [comment]
Yes so that certification means it's certified with the pre-install image.  if you purchase it with Ubuntu you'll have the image already created (which uses this recovery software).  You can also get it from support.dell.com as well if you put in your service tag purchased with Ubuntu.

In "general" fixes make it into later Ubuntu releases, but it does sound like you found a situation that nouveau is unstable causing problems.  What you can do is boot with "nomodeset" on the kernel command line to try to work around this behavior.  That should get you installed and you can try to install the oem kernel and binary nvidia driver and that may help.

**Comment by forestjohnsonpeoplenet** [comment]
Thanks. Thats exactly what I ended up doing.   

The nvidia official driver did not work, but I was able to get hardware acceleration working by using the ubuntu graphics-drivers ppa

https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa
