### ISSUE TITLE
dell-recovery 1.63 depends on python 3.7 unavailable in bionic

### ISSUE THREAD

**Issue by coroa** [dell/dell-recovery#87]
dell-recovery 1.63 does not work on bionic-based Recovery medias as the image for Dell XPS 9380, which is based on ubuntu bionic where the latest available python version is 3.7.

Refer also to https://github.com/dell/dell-recovery/commit/b8dce586d4154c45c2bcdb686911669e655949e0#r35569513

**Comment by superm1** [comment]
Apologies that this breakage happened, it was part of getting dell-recovery ready for newer Ubuntu releases.
If that's the only breakage, I'll tag a new release.
